### ISSUE TITLE
sendAllLoadStat，loadScript，loadImage

### ISSUE THREAD

**Issue by panhezeng** [shenfe/stat.js#4]
sendAllLoadStat方法，在严格模式下，声明函数内不能再使用声明函数，可以改成表达式var sendAllLoadStat = function () {}

loadScript和loadImage，每次send都会创建一个元素，特别是script元素会越来越多。建议提取出来创建。

比如
var stat_script_el = document.createElement('script');
          (document.getElementsByTagName('head')[0] || document.body).appendChild(stat_script_el);
function loadScript(url, callback) {}

**Comment by shenfe** [comment]
谢谢您的意见，我已对程序作了相应改进。
